global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    # Для macOS добавьте:
    extra_hosts:
      - "host.docker.internal:host-gateway"